name: Build

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          go get -d -v
          go build -v .
