name: Integration Test

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Self test
        uses: thijsvtol/create-environments@main
        with:
          token: ${{ secrets.GHP }}
          repo: ${{ github.repository }}
          environments: test, prod
          # required_reviewers: thijsvtol
          # wait_time: 1
